/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace user {
    export interface UserService {
        findOne(
            data: UserByUuid,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<User>;
        findAll(
            data: Observable<UserByUuid>,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<User>;
    }
    export interface UserByUuid {
        uuid?: string;
    }
    export interface User {
        uuid?: string;
        name?: string;
        email?: string;
        createdAt?: string;
        updatedAt?: string;
    }
}

